name: Reusable Deploy
on: 
  workflow_call: # allows this workflow to be called from other workflow
    inputs: # ← defines what data caller can pass in
            # like function parameters in programming
        artifact-name:  # ← the parameter name
                        # caller uses this name to pass a value
            description: The name of the deployable artifact file    
            required: false 
            default: dist
            type: string   
    outputs: # exposes deploy job output to the caller workflow
        result:
            description: The result of the deployment operation
            value: ${{jobs.deploy.outputs.outcome}} #reusable workflow uses "jobs.jobname"

    # secrets: # ← sensitive data, masked in logs       
    #     some-secret:
    #         required: false 
            
jobs:

    deploy:
        outputs: 
            outcome: ${{steps.Output-step.outputs.step-result}} # ← exposes to other jobs
        runs-on: ubuntu-latest
        steps:

            - name: Get Code
              uses: actions/download-artifact@v8
              with:
                name: ${{ inputs.artifact-name}}  # ← reads the input value
                                                  # → 'dist-files' if passed, 'dist' if not
            
            - name: List files
              run: ls

            - name: Output info
              run: echo "Output" 

            - name: Set output
              id: Output-step  # ← id referenced in outputs above
              run: echo "step-result=success" >> $GITHUB_OUTPUT
               

